<div class="container">
    <div class="row">
        <?php $this->headTitle($title); ?>
        <h1><?php echo $this->escapeHtml($title); ?></h1>
        <?php
        $form->setAttribute('action', $this->url('items', ['action' => 'edit', 'id' => $item->getId()]));
        $form->prepare();

        $form->get('submit')->setValue('Update Post');

        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag();
        ?>
    </div>
</div>
