<div class="container">
    <div class="row">
        <?php $this->headTitle($title); ?>
        <h1><?php echo $this->escapeHtml($title); ?></h1>

        <table class="table">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Rate</th>
                <th>Created</th>
            </tr>
            <tr>
                <td>1</td>
                <td>Foo</td>
                <td>2.55</td>
                <td>July 9</td>
            </tr>
            <tr>
                <td>1</td>
                <td>Foo</td>
                <td>2.55</td>
                <td>July 9</td>
            </tr>
        </table>
        <div>
            <a class="btn btn-default" href="<?php echo $this->url('items', ['action' => 'add']); ?>">Create New</a>
        </div>
    </div>
</div>
