<div class="container">
    <div class="row">
        <?php $this->headTitle($title); ?>
        <h1><?php echo $this->escapeHtml($title); ?></h1>

        <?php if (empty($items)): ?>
            <div class="alert alert-info"><?php echo $this->translate('no_records_found') ?></div>
        <?php else: ?>
            <div>
                Total Records: <?php echo $total ?>
            </div>
            <?php if ($noOfPages > 1): ?>
                <nav>
                    <ul class="pagination">
                        <?php if (isset($links['prev'])): ?>
                            <li>
                                <a href="<?php echo $links['prev'] ?>" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        <?php endif; ?>

                        <?php for ($p = 1; $p <= $noOfPages; $p++): ?>
                            <li class="<?php echo $p == $page ? 'active' : '' ?>">
                                <a href="<?php echo $pageLink($p) ?>"><?php echo $p ?></a>
                            </li>
                        <?php endfor; ?>

                        <?php if (isset($links['next'])): ?>
                            <li>
                                <a href="<?php echo $links['next'] ?>" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </nav>
            <?php endif; ?>
            <table class="table">
                <tr>
                    <th>Role</th>
                    <th>Parent</th>
                    <th>Created</th>
                    <th></th>
                </tr>
                <?php foreach ($items as $item): ?>
                    <tr>
                        <td><?php echo $item->getRoleId() ?></td>
                        <td><?php echo ($parent = $item->getParent()) ? $parent->getRoleId() : '' ?></td>
                        <td><?php echo $item->getCreated()->format('M d, Y h:i:s A') ?></td>
                        <td>
                            <a class="btn btn-sm btn-default" href="<?php echo $this->url('roles', ['action' => 'edit', 'id' => $item->getId()]); ?>">Edit</a>
                            <a class="btn btn-sm btn-default" href="<?php echo $this->url('roles', ['action' => 'delete', 'id' => $item->getId()]); ?>">Delete</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php endif; ?>
        <div>
            <a class="btn btn-default" href="<?php echo $this->url('roles', ['action' => 'add']); ?>">Create New</a>
        </div>
    </div>
</div>
