<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',])
        ->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', ['conditional' => 'lt IE 9',]); ?>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img
                    src="<?php echo $this->basePath('img/zf2-logo.png') ?>"
                    alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
        </div>
        <div class="collapse navbar-collapse clearfix">
            <?php echo $this->navigation('navigation')
                ->menu()
                ->setMinDepth(0)
                ->setMaxDepth(0)
                ->setUlClass('nav navbar-nav');
            ?>
            <ul class="navbar-nav nav pull-right">
                <?php if ($this->zfcUserIdentity()) { ?>
                    <li><a href="<?php echo $this->url('zfcuser'); ?>">My Profile</a></li>
                    <li><a href="<?php echo $this->url('zfcuser/logout'); ?>">Logout</a></li>
                <?php } else { ?>
                    <li><a href="<?php echo $this->url('zfcuser/login'); ?>">Login</a></li>
                    <li><a href="<?php echo $this->url('zfcuser/register'); ?>">Register</a></li>
                <?php } ?>
            </ul>
        </div>
        <!--/.nav - collapse-->
    </div>
</nav>
<div class="container">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies
            Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div>
<!-- /container -->
<?php echo $this->inlineScript() ?>
<?php echo $this->headScript()->appendFile($this->basePath('js/application/confirm-delete.js')) ?>
</body>
</html>
